version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: 'postgres'
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart:
      'always'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    depends_on:
      - postgres

#  frontend:
#    build: './frontend'
#    ports:
#      - '3000:3000'

volumes:
  postgres_db: